import type { NextPage } from 'next'
import Head from 'next/head'
const Home: NextPage = () => {
  return (
    <div className="h-screen flex flex-col bg-gray-100">
      <Head>
        <title>NextJs - Boilerplate</title>
        <meta name="description" content="Generated by Lucas Couto" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1 items-center justify-center">
        <h1 className="font-bold text-5xl">Welcome to NextJs Boilerplate</h1>
      </div>
      <footer className="flex justify-center py-4 border-t border-t-gray-600">
        <p>Powered by Lucas Couto</p>
      </footer>
    </div>
  )
}

export default Home
